List<String> hukukAlanlari = [
  'Ceza Hukuku',
  'Anayasa Hukuku',
  'Medeni Hukuk',
  'İdare Hukuku',
  'Borçlar Hukuku',
  'Sözleşme Hukuku',
  'Fikri Mülkiyet Hukuku',
  'Uluslararası Hukuk',
  'İş Hukuku',
  'Ticaret Hukuku',
  'Vergi Hukuku',
  'Deniz Hukuku',
  'Hava Hukuku',
  'Çevre Hukuku',
  'Enerji Hukuku',
  'Gümrük Hukuku',
  'Özel Hukuk',
  'Kamu Hukuku',
  'Askeri Hukuk',
  'Aile Hukuku',
  'Miras Hukuku',
  'İmar Hukuku',
  'Gayrimenkul Hukuku',
  'Emlak Hukuku',
  'Kişisel Verilerin Korunması Hukuku',
  'Kişisel Haklar Hukuku',
  'İşçi Sağlığı ve İş Güvenliği Hukuku',
  'Patent Hukuku',
  'Marka Hukuku',
  'Toplantı ve Gösteri Hakkı Hukuku',
  'Basın Hukuku',
  'İfade Özgürlüğü Hukuku',
  'Engellilerin Hakları Hukuku',
  'Hayvan Hakları Hukuku',
  'Çocuk Hakları Hukuku',
  'Mülteci Hukuku',
  'Tarım Hukuku',
  'Gıda Hukuku',
  'Eğitim Hukuku',
  'Gençlik Hukuku',
  'Sosyal Hizmetler Hukuku',
  'Turizm Hukuku',
  'Sağlık Hukuku',
  'Bankruptcy Hukuku',
  'Uluslararası Ticaret Hukuku',
  'İnternet Hukuku',
  'Uzlaştırma Hukuku',
  'Enerji ve Tabii Kaynaklar Hukuku',
  'Borç İlişkileri Hukuku',
  'Kamu İhale Hukuku',
  'İşletme Hukuku',
  'İşletme Sermayesi Hukuku',
  'Ticari Mülkiyet Hukuku',
  'Telif Hukuku',
  'Uluslararası Özel Hukuk',
  'İşletme Vergi Hukuku',
  'İşletme İdare Hukuku',
  'Lojistik Hukuku',
  'Konut Hukuku',
  'Gayrimenkul Devri Hukuku',
  'Yer Altı Kaynakları Hukuku',
  'İnşaat Hukuku',
  'Fintech Hukuku',
  'Havacılık Hukuku',
  'Deniz Ticaret Hukuku',
  'Gemi İnşa Hukuku',
  'Maliye Hukuku',
  'Sigorta Hukuku',
  'Rekabet Hukuku',
  'Bankacılık Hukuku',
  'Yabancılar Hukuku',
  'Uluslararası İş Hukuku',
  'Gümrük Vergisi Hukuku',
  'Kıyı Hukuku',
  'Deniz Kirliliği Hukuku',
  'Yeraltı Suyu Hukuku',
  'Telekomünikasyon Hukuku',
  'Güvenlik Hukuku',
  'Yatırım Hukuku',
  'Muhasebe Hukuku',
  'Enerji Piyasası Hukuku',
  'Hakem Hukuku',
  'Uluslararası Tahkim Hukuku',
  'Hayır Kurumları Hukuku',
  'Kültür ve Sanat Hukuku',
  'Sporda Hukuk',
  'Tarım ve Köy İşleri Hukuku',
  'Sağlık Sigortası Hukuku',
  'Banka Sigortası Hukuku',
  'Konkordato Hukuku',
  'Deniz Taşımacılığı Hukuku',
  'Enerji Yatırımı Hukuku',
  'Fikri Mülkiyet İnternet Hukuku',
  'Sınır Tanımayan İşletmeler Hukuku',
  'Telekomünikasyon ve İnternet Hukuku',
  'Finansal Kurumlar Hukuku',
  'Ticaretin Düzenlenmesi Hukuku',
  'Türk Hava Yolu İşletmesi Hukuku',
  'Esnaf ve Sanatkarlar Hukuku',
  'Tüketicinin Korunması Hukuku',
  'Medya Hukuku',
  'Denizde Güvenlik Hukuku',
  'Deniz İşletmeciliği Hukuku',
  'Kamu İdareleri Hukuku',
  'Kıyı ve Deniz Turizmi Hukuku',
  'Sermaye Piyasası Hukuku',
  'Özelleştirme Hukuku',
  'Kültür Varlıkları Koruma Hukuku',
  'Kültür Varlıklarının Korunması Hukuku',
  'Hazine Hukuku',
  'Kısmi Süreli Çalışma Hukuku',
  'Toplumsal Cinsiyet Hukuku',
  'Sınai Mülkiyet Hukuku',
  'Güvenlik Soruşturması ve Arşiv Araştırması Hukuku',
  'Göç Hukuku',
  'Turizm Yatırım Hukuku',
  'Yabancı Yatırım Hukuku',
];
