// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAbHe1JaJDlsFyexGXZMp6zBOQOESbHPn8',
    appId: '1:63850141999:web:5a44b7c4b3ad94a55ce9da',
    messagingSenderId: '63850141999',
    projectId: 'avukapp-457a2',
    authDomain: 'avukapp-457a2.firebaseapp.com',
    storageBucket: 'avukapp-457a2.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBn3uTHHUpRK-wVnkCvR3zAs0HGN4OheCA',
    appId: '1:63850141999:android:381a00a14b0b6df45ce9da',
    messagingSenderId: '63850141999',
    projectId: 'avukapp-457a2',
    storageBucket: 'avukapp-457a2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDfm4A3muOlVQv7ZYM63HX29t-YtZUdDyQ',
    appId: '1:63850141999:ios:a3789a8c742459fe5ce9da',
    messagingSenderId: '63850141999',
    projectId: 'avukapp-457a2',
    storageBucket: 'avukapp-457a2.appspot.com',
    iosClientId: '63850141999-ot7g88sk0ghcdvbtm7vraacdousd7mlg.apps.googleusercontent.com',
    iosBundleId: 'com.example.avukapp',
  );
}
